version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Deploying new frontend
      - aws s3 sync ./build s3://my-sample-testing-codepipeline-artifacts --delete